const Schema=require("mongoose").Schema;
const transactionSchema=require("./transaction.js").transactionSchema;

const creditSchema=new Schema({
    Number:{
        type:Number,
        required:true,
        autoGenerated:true,
        // unique:true
    },
    Type:{
        type:String,
        required:true,
    },
    cvv:{
        type:Number,
        required:true
    },
    ExpiryDate:{
        type:Date,
        required:true
    },
    Balance:{
        type:Number,
        required:true
    },
    Status:{
        type:String,
    },
    Transactions:{
        type:[transactionSchema],
        required:false
    },
});

module.exports={creditSchema};